server:
  port: 8091

spring:
  application:
    name: catalog-service

  # Cloud Config (client side)
  config:
    import: optional:configserver:http://localhost:8071

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: demo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    # leave these false for safety; only flip to true intentionally
    baseline-on-migrate: false
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.flywaydb: INFO

# --- Actuator web exposure (so /actuator/env works) ---
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    env:
      show-values: ALWAYS   # consider WHEN_AUTHORIZED in real environments
