server:
  port: 8089

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  health:
    probes:
      enabled: true

logging:
  level:
    com.example.demo: INFO

feature:
  exampleFlag: true
